addons:
  sonarcloud:
    organization: "sebas-mora28"
    token: "e6MLE2piNzdt09Stku+pjNc9uDQBbs/8CaY9x9Klns0MGxKH/ymyvl8b5H0Wqsn/9NoSkRuUsFeHDfPTUcsXpbFejQNVRpiJFeOYPVdTe2QBpsGwmekt5l9xyxQ2yE1v8GnwbaK5i7kuraPUDeryF8j1+BQ2Na7fZh1YATTsup83SqNvksIowAurJjaHwSxQlriF1LUGn6IlPOZbMvY4fYIG7H0bX6WjYH4+OnEPwWZaSDeCttPSLRVZmJL9vPTU2k1sy2n3EWwv1F651TU0cF9NLdoZ9NGQa3tIhLJZbbpkuljnEaePQgxIPnbqdwA91vN8Pwbkk29bu3v/uXTbPqRiO6pogzQTm8jAX1RxOpY8eerRKrh10tvpwKMmorEp7FG6nSrbqDsKy0feHnBkQZMlTV+vmtqVGkSSS2dnfiQX1XjJ+uwsnt2Uzvm0/tfQS04An/w/Fa0e6+PzW8y6DF6SDX3aZ9FZe9tJeex+2hXli3wyrDW2eKyndil8N45CxE2F/vaqfZ9UMv7oincoRgwUUHM++MP1Hz+yIlfHbVi+QGKHa9gLHn82qx7K7QdWvmRBzxScTIUhQrl1M1fK46qVb4Dq/uV0NOb1zR1d/pyLIesOGRRxMJ/GzR7VkTHZnb90V0kdJOeUtCvEbQxBHpAJd37v8kybb5k4fQjXoLQ="

language:
  java

script:
  - ant dist
  - sonar-scanner


















